@local=http://localhost:3001
 @token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGI2NTg3NzYyZTZhZmYyOWUxZmNkNzIiLCJiaXoiOnRydWUsImlhdCI6MTY5MDg4OTE4MH0.9gxjAp79Y7GhGvjqPHzDunitdHUPziKQe_GubqOwt60
//Content-Type: application/json
###
//send new user (sign in) request
POST {{local}}/users
Content-Type: application/json

{
    "name": "sagi4",
    "password": "Levy111",
    "email": "sagi4@gmail.com",
    "biz": true
  }
###


//sent req for auth (log in)
POST {{local}}/auth
Content-Type: application/json
 
{
    "password": "Levy111",
    "email": "sagi4@gmail.com"
}






###


GET {{local}}/users/me
x-auth-token:{{token}}



















###
GET {{local}}/users/me
x-auth-token:{{token}}





###
// send card req
POST {{local}}/cards/create-activity-card
x-auth-token:{{token}}
Content-Type: application/json

{
    "activityName": "paintball game 1",
    "bizUserName": "sagi levy",
    "activityDescription":"first paintball game card (activity card)",
    "activityAddress": "kfar sava ",
    "bizUserPhone": "0545454545",
    "activityImage":"https://media.istockphoto.com/id/1349643226/photo/team-of-friends-paintball-players-playing-together-in-battle.jpg?s=2048x2048&w=is&k=20&c=0_TPof3tWNS4hHegpZtRRRUt7bu9IjepYh6caJqhnkk=" 
  }

###
GET {{local}}/cards/my-activity-cards/64b9003af91e360079aa14e7
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGI2NTg3NzYyZTZhZmYyOWUxZmNkNzIiLCJiaXoiOnRydWUsImlhdCI6MTY4OTg0NTEwNn0.DBl3sPfucVrgf4s2cqtppsK7CjgUgW3BmOUSLxV9iWY
Content-Type: application/json



###
DELETE {{local}}/cards/delete-activity-cards/64c8ec73fc6e1f5e55d01c17
x-auth-token:{{token}}
Content-Type: application/json

###

POST {{local}}/cards/create-activity-card
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGI2NTg3NzYyZTZhZmYyOWUxZmNkNzIiLCJiaXoiOnRydWUsImlhdCI6MTY4OTg0NTEwNn0.DBl3sPfucVrgf4s2cqtppsK7CjgUgW3BmOUSLxV9iWY
Content-Type: application/json

{
    "activityName": "paintball game 1",
    "bizUserName": "מנשששש",
    "activityDescription":"first paintball game card (activity card)",
    "activityAddress": "kfar sava ",
    "bizUserPhone": "0545454545",
    "activityDate":"05/22/2024",
    "activityImage":"https://media.istockphoto.com/id/1349643226/photo/team-of-friends-paintball-players-playing-together-in-battle.jpg?s=2048x2048&w=is&k=20&c=0_TPof3tWNS4hHegpZtRRRUt7bu9IjepYh6caJqhnkk=" 
  }






###
GET {{local}}/users/me
x-auth-token:{{token}}

###
# GET {{local}}/cards/my-activity-cards1
# x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDRmYzYyNWIyOTI2MWVkYzA1ZjJmNDIiLCJiaXoiOmZhbHNlLCJpYXQiOjE2ODI5NTU3MjF9.CgS4eZWZA_pfBS07HRQSBDn7CJoSIz5X3NwKdfYKYZo
# Content-Type: application/json




###
GET {{local}}/cards/my-activity-cards/64b6587762e6aff29e1fcd72
x-auth-token:{{token}}
Content-Type: application/json

